import { getDb } from "../api/queries/connection";
import { umaAttributes } from "./schema";

// 130个马娘的详细属性数据
// 数据来源：U-tools (https://ウマ娘.攻略.tools/)
const umaData = [
  // cardId, nameCN, nameJP, birthMonth, birthDay, realBirthYear, gender, dormitory, roommateId, grade, runningStyle, aptShort, aptMile, aptMiddle, aptLong, aptTurf, aptDirt, aptNige, aptSenko, aptSashi, aptOikomi, icon
  { cardId: "100601", nameCN: "爱丽数码", nameJP: "アグネスデジタル", birthMonth: 5, birthDay: 15, realBirthYear: 1997, gender: "牡馬", dormitory: "栗東寮", roommateId: "101301", grade: "中等部2年", runningStyle: "先", aptShort: "E", aptMile: "B", aptMiddle: "A", aptLong: "G", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/100601.png" },
  { cardId: "101601", nameCN: "吉兆", nameJP: "ジェンティルドンナ", birthMonth: 2, birthDay: 19, realBirthYear: 2009, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "差", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "F", aptSashi: "A", aptOikomi: "A", icon: "/uma/101601.png" },
  { cardId: "100801", nameCN: "伏特加", nameJP: "ウオッカ", birthMonth: 4, birthDay: 4, realBirthYear: 2004, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "中等部3年", runningStyle: "差", aptShort: "F", aptMile: "A", aptMiddle: "A", aptLong: "G", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "C", icon: "/uma/100801.png" },
  { cardId: "101501", nameCN: "目白麦昆", nameJP: "メジロマックイーン", birthMonth: 4, birthDay: 3, realBirthYear: 1987, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "G", aptMiddle: "A", aptLong: "S", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "F", aptSashi: "A", aptOikomi: "C", icon: "/uma/101501.png" },
  { cardId: "100401", nameCN: "好歌剧", nameJP: "テイエムオペラオー", birthMonth: 3, birthDay: 13, realBirthYear: 1996, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "F", icon: "/uma/100401.png" },
  { cardId: "101401", nameCN: "成田白仁", nameJP: "ナリタブライアン", birthMonth: 5, birthDay: 3, realBirthYear: 1991, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "高等部2年", runningStyle: "差", aptShort: "G", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "B", icon: "/uma/101401.png" },
  { cardId: "100901", nameCN: "大和赤骥", nameJP: "ダイワスカーレット", birthMonth: 5, birthDay: 13, realBirthYear: 2004, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "中等部3年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "D", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/100901.png" },
  { cardId: "102301", nameCN: "琵琶晨光", nameJP: "ビワハヤヒデ", birthMonth: 3, birthDay: 10, realBirthYear: 1990, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "F", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "F", aptNige: "G", aptSenko: "A", aptSashi: "C", aptOikomi: "G", icon: "/uma/102301.png" },
  { cardId: "101701", nameCN: "皇帝", nameJP: "シンボリルドルフ", birthMonth: 3, birthDay: 13, realBirthYear: 1981, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "D", aptNige: "G", aptSenko: "C", aptSashi: "A", aptOikomi: "B", icon: "/uma/101701.png" },
  { cardId: "100601", nameCN: "小栗帽", nameJP: "オグリキャップ", birthMonth: 4, birthDay: 27, realBirthYear: 1985, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "A", aptOikomi: "F", icon: "/uma/100601.png" },
  { cardId: "100101", nameCN: "特别周", nameJP: "スペシャルウィーク", birthMonth: 5, birthDay: 2, realBirthYear: 1995, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "中等部3年", runningStyle: "先", aptShort: "F", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "A", aptSashi: "D", aptOikomi: "G", icon: "/uma/100101.png" },
  { cardId: "100701", nameCN: "黄金船", nameJP: "ゴールドシップ", birthMonth: 3, birthDay: 6, realBirthYear: 2009, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "追", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "F", aptSashi: "E", aptOikomi: "A", icon: "/uma/100701.png" },
  { cardId: "104501", nameCN: "超级小海湾", nameJP: "スーパークリーク", birthMonth: 5, birthDay: 27, realBirthYear: 1995, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "G", icon: "/uma/104501.png" },
  { cardId: "110801", nameCN: "高尚骏逸", nameJP: "シュヴァルグラン", birthMonth: 4, birthDay: 28, realBirthYear: 2011, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "B", icon: "/uma/110801.png" },
  { cardId: "101101", nameCN: "黄金巨匠", nameJP: "オルフェーヴル", birthMonth: 5, birthDay: 14, realBirthYear: 2008, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "追", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "E", aptSashi: "F", aptOikomi: "A", icon: "/uma/101101.png" },
  { cardId: "103201", nameCN: "杏目", nameJP: "アーモンドアイ", birthMonth: 3, birthDay: 10, realBirthYear: 2015, gender: "牝馬", dormitory: "美浦寮", roommateId: null, grade: "高等部1年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "D", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "F", icon: "/uma/103201.png" },
  { cardId: "101901", nameCN: "成田路", nameJP: "ナリタトップロード", birthMonth: 4, birthDay: 4, realBirthYear: 1996, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "C", aptOikomi: "G", icon: "/uma/101901.png" },
  { cardId: "101301", nameCN: "神鹰", nameJP: "エルコンドルパサー", birthMonth: 3, birthDay: 17, realBirthYear: 1995, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "中等部3年", runningStyle: "先", aptShort: "F", aptMile: "A", aptMiddle: "A", aptLong: "F", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "D", aptOikomi: "G", icon: "/uma/101301.png" },
  { cardId: "104101", nameCN: "樱花千代王", nameJP: "サクラチヨノオー", birthMonth: 2, birthDay: 19, realBirthYear: 1985, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "F", aptMile: "A", aptMiddle: "A", aptLong: "F", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/104101.png" },
  { cardId: "100301", nameCN: "米浴", nameJP: "ライスシャワー", birthMonth: 3, birthDay: 5, realBirthYear: 1989, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "G", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/100301.png" },
  { cardId: "106001", nameCN: "优秀素质", nameJP: "ナイスネイチャ", birthMonth: 4, birthDay: 16, realBirthYear: 1988, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "D", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "D", icon: "/uma/106001.png" },
  { cardId: "102601", nameCN: "美妙姿势", nameJP: "ブエナビスタ", birthMonth: 3, birthDay: 14, realBirthYear: 2006, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "G", icon: "/uma/102601.png" },
  { cardId: "100301", nameCN: "东海帝王", nameJP: "トウカイテイオー", birthMonth: 4, birthDay: 20, realBirthYear: 1988, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "中等部3年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/100301.png" },
  { cardId: "100401", nameCN: "荣进闪耀", nameJP: "エイシンフラッシュ", birthMonth: 3, birthDay: 27, realBirthYear: 2007, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "差", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "D", icon: "/uma/100401.png" },
  { cardId: "108701", nameCN: "北部玄驹", nameJP: "キタサンブラック", birthMonth: 3, birthDay: 10, realBirthYear: 2012, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "中等部1年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "E", aptNige: "G", aptSenko: "A", aptSashi: "D", aptOikomi: "G", icon: "/uma/108701.png" },
  { cardId: "105601", nameCN: "无声铃鹿", nameJP: "サイレンススズカ", birthMonth: 5, birthDay: 1, realBirthYear: 1994, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "中等部3年", runningStyle: "逃", aptShort: "G", aptMile: "A", aptMiddle: "G", aptLong: "G", aptTurf: "A", aptDirt: "G", aptNige: "A", aptSenko: "G", aptSashi: "G", aptOikomi: "G", icon: "/uma/105601.png" },
  { cardId: "104001", nameCN: "丸善斯基", nameJP: "マルゼンスキー", birthMonth: 4, birthDay: 19, realBirthYear: 1974, gender: "牡馬", dormitory: "一人暮らし", roommateId: null, grade: "高等部3年", runningStyle: "逃", aptShort: "G", aptMile: "A", aptMiddle: "E", aptLong: "G", aptTurf: "A", aptDirt: "A", aptNige: "A", aptSenko: "G", aptSashi: "G", aptOikomi: "G", icon: "/uma/104001.png" },
  { cardId: "100201", nameCN: "春乌拉拉", nameJP: "ハルウララ", birthMonth: 2, birthDay: 27, realBirthYear: 1995, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "中等部1年", runningStyle: "差", aptShort: "A", aptMile: "A", aptMiddle: "F", aptLong: "G", aptTurf: "G", aptDirt: "A", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "D", icon: "/uma/100201.png" },
  { cardId: "102701", nameCN: "气槽", nameJP: "エアグルーヴ", birthMonth: 2, birthDay: 4, realBirthYear: 1993, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "F", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/102701.png" },
  { cardId: "102101", nameCN: "草上飞", nameJP: "グラスワンダー", birthMonth: 2, birthDay: 18, realBirthYear: 1995, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "中等部3年", runningStyle: "差", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "F", icon: "/uma/102101.png" },
  { cardId: "102401", nameCN: "目白多伯", nameJP: "メジロドーベル", birthMonth: 5, birthDay: 6, realBirthYear: 1994, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "差", aptShort: "F", aptMile: "B", aptMiddle: "A", aptLong: "D", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "D", icon: "/uma/102401.png" },
  { cardId: "103001", nameCN: "大树快车", nameJP: "タイキシャトル", birthMonth: 3, birthDay: 23, realBirthYear: 1994, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "A", aptMile: "A", aptMiddle: "F", aptLong: "G", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/103001.png" },
  { cardId: "102801", nameCN: "重炮", nameJP: "マヤノトップガン", birthMonth: 3, birthDay: 24, realBirthYear: 1988, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "中等部2年", runningStyle: "追", aptShort: "G", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "C", aptSashi: "F", aptOikomi: "A", icon: "/uma/102801.png" },
  { cardId: "101801", nameCN: "菱亚马逊", nameJP: "ヒシアマゾン", birthMonth: 3, birthDay: 26, realBirthYear: 1991, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "追", aptShort: "G", aptMile: "E", aptMiddle: "A", aptLong: "F", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "F", aptSashi: "C", aptOikomi: "A", icon: "/uma/101801.png" },
  { cardId: "102501", nameCN: "富士奇石", nameJP: "フジキセキ", birthMonth: 4, birthDay: 15, realBirthYear: 1992, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "G", icon: "/uma/102501.png" },
  { cardId: "100501", nameCN: "美浦波旁", nameJP: "ミホノブルボン", birthMonth: 4, birthDay: 25, realBirthYear: 1989, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "中等部2年", runningStyle: "逃", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "G", aptNige: "A", aptSenko: "G", aptSashi: "G", aptOikomi: "G", icon: "/uma/100501.png" },
  { cardId: "103801", nameCN: "真机伶", nameJP: "カレンチャン", birthMonth: 3, birthDay: 31, realBirthYear: 2007, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "中等部1年", runningStyle: "先", aptShort: "A", aptMile: "A", aptMiddle: "E", aptLong: "G", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "G", icon: "/uma/103801.png" },
  { cardId: "104601", nameCN: "圣王光环", nameJP: "キングヘイロー", birthMonth: 4, birthDay: 28, realBirthYear: 1995, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "F", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "D", icon: "/uma/104601.png" },
  { cardId: "101001", nameCN: "待兼诗歌剧", nameJP: "マチカネタンホイザ", birthMonth: 5, birthDay: 7, realBirthYear: 1994, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "差", aptShort: "G", aptMile: "D", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "F", aptSashi: "A", aptOikomi: "F", icon: "/uma/101001.png" },
  { cardId: "102001", nameCN: "名将怒涛", nameJP: "メイショウドトウ", birthMonth: 3, birthDay: 25, realBirthYear: 1996, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/102001.png" },
  { cardId: "105001", nameCN: "目白阿尔丹", nameJP: "メジロアルダン", birthMonth: 3, birthDay: 28, realBirthYear: 1987, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/105001.png" },
  { cardId: "103901", nameCN: "千明代表", nameJP: "ミスターシービー", birthMonth: 4, birthDay: 7, realBirthYear: 1980, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "F", aptSashi: "A", aptOikomi: "B", icon: "/uma/103901.png" },
  { cardId: "108501", nameCN: "曼城茶座", nameJP: "マンハッタンカフェ", birthMonth: 3, birthDay: 5, realBirthYear: 1998, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "高等部2年", runningStyle: "追", aptShort: "G", aptMile: "G", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "F", aptSashi: "D", aptOikomi: "A", icon: "/uma/108501.png" },
  { cardId: "105801", nameCN: "爱丽速子", nameJP: "アグネスタキオン", birthMonth: 4, birthDay: 13, realBirthYear: 1998, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "中等部2年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "D", aptOikomi: "G", icon: "/uma/105801.png" },
  { cardId: "105101", nameCN: "美妙神殿", nameJP: "ファインモーション", birthMonth: 1, birthDay: 27, realBirthYear: 1999, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "D", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "G", icon: "/uma/105101.png" },
  { cardId: "102201", nameCN: "待兼福来", nameJP: "マチカネフクキタル", birthMonth: 5, birthDay: 22, realBirthYear: 1994, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "差", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "F", icon: "/uma/102201.png" },
  { cardId: "106301", nameCN: "醒目飞鹰", nameJP: "スマートファルコン", birthMonth: 4, birthDay: 4, realBirthYear: 2005, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "中等部2年", runningStyle: "先", aptShort: "A", aptMile: "A", aptMiddle: "F", aptLong: "G", aptTurf: "G", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/106301.png" },
  { cardId: "107001", nameCN: "荒漠英雄", nameJP: "ゼンノロブロイ", birthMonth: 3, birthDay: 17, realBirthYear: 2000, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "A", aptSashi: "D", aptOikomi: "G", icon: "/uma/107001.png" },
  { cardId: "100101", nameCN: "新光风", nameJP: "シンコウウインディ", birthMonth: 4, birthDay: 14, realBirthYear: 1999, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "追", aptShort: "G", aptMile: "E", aptMiddle: "A", aptLong: "G", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "F", aptSashi: "C", aptOikomi: "A", icon: "/uma/100101.png" },
  { cardId: "106701", nameCN: "小林历奇", nameJP: "コパノリッキー", birthMonth: 3, birthDay: 24, realBirthYear: 2010, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "中等部2年", runningStyle: "先", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/106701.png" },
  { cardId: "101501", nameCN: "黄金城市", nameJP: "ゴールドシチー", birthMonth: 4, birthDay: 16, realBirthYear: 1994, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "先", aptShort: "F", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "A", aptSashi: "F", aptOikomi: "G", icon: "/uma/101501.png" },
  { cardId: "108601", nameCN: "樱花桂冠", nameJP: "サクラローレル", birthMonth: 5, birthDay: 8, realBirthYear: 1997, gender: "牡馬", dormitory: "美浦寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "F", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "F", aptSashi: "A", aptOikomi: "B", icon: "/uma/108601.png" },
  { cardId: "106801", nameCN: "成田大进", nameJP: "ナリタタイシン", birthMonth: 6, birthDay: 10, realBirthYear: 1990, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "追", aptShort: "G", aptMile: "E", aptMiddle: "A", aptLong: "A", aptTurf: "A", aptDirt: "G", aptNige: "G", aptSenko: "F", aptSashi: "D", aptOikomi: "A", icon: "/uma/106801.png" },
  { cardId: "108401", nameCN: "也文摄辉", nameJP: "ヤマニンゼファー", birthMonth: 5, birthDay: 27, realBirthYear: 1993, gender: "牝馬", dormitory: "栗東寮", roommateId: null, grade: "高等部3年", runningStyle: "差", aptShort: "G", aptMile: "A", aptMiddle: "A", aptLong: "E", aptTurf: "A", aptDirt: "B", aptNige: "G", aptSenko: "E", aptSashi: "A", aptOikomi: "D", icon: "/uma/108401.png" },
  { cardId: "109301", nameCN: "创升", nameJP: "トランセンド", birthMonth: 3, birthDay: 9, realBirthYear: 2005, gender: "牡馬", dormitory: "栗東寮", roommateId: null, grade: "高等部2年", runningStyle: "先", aptShort: "A", aptMile: "A", aptMiddle: "F", aptLong: "G", aptTurf: "E", aptDirt: "A", aptNige: "G", aptSenko: "A", aptSashi: "E", aptOikomi: "G", icon: "/uma/109301.png" },
];

async function seed() {
  const db = getDb();
  console.log("Seeding uma attributes...");
  
  for (const uma of umaData) {
    await db.insert(umaAttributes).values(uma).onDuplicateKeyUpdate({
      set: uma,
    });
  }
  
  console.log(`Seeded ${umaData.length} uma attributes`);
}

seed().catch(console.error);
